[build.environment]
  YARN_VERSION = "1.12.1"
  NPM_VERSION = "6.4.1"
  HUGO_VERSION = "0.55.6"

[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build:preview"

[[headers]]
  for = "/images/*"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/images/uploads/*"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.jpg"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.css"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.js"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.html"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''



