baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Marmalade Game Studio"

[imaging]
quality = 60

# Google
#
googleAnalytics = "UA-150749173-1"
#google_verify_meta = "//BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

# site custom main menu
[menu]
    [[menu.navbar]]
        identifier = "services"
        name = "Services"
        url = "/services"
        weight = 1
    [[menu.navbar]]
        identifier = "case_studies"
        name = "Case Studies"
        url = "/case-studies"
        weight = 2
    [[menu.navbar]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 3
    [[menu.navbar]]
        identifier = "contact"
        name = "Contact"
        url = "/contact"
        weight = 4
    [[menu.secondary]]
        identifier = "privacy"
        name = "Privacy Policy"
        url = "/privacy"
        weight = 1
    [[menu.secondary]]
        identifier = "app-privacy"
        name = "App Privacy Policy"
        url = "/app-privacy"
        weight = 2
# Privacy

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false

[params]
    custom_navbar= false
    cms_navbar = true
    host_name = "https://eloquent-curran-2d10a7.netlify.com"
    description = "Marmalade Game Studio was founded on a passion and commitment to create great gameplay experiences for mobile and connected devices. We prototype, reflect, and test with target audiences to craft games that people love to play. Headquartered in London, UK with a further studio in Lisbon, Portugal, our goal is to continuously develop compelling high…"
    logo_large="/images/logo-full.png"
    logo_small="/images/logo-icon.png"
    logo_mobile="/images/logo-full.png"
    logo_large_invert="/images/logo-icon.png"
